#!/bin/sh
. "$(dirname $0)/_/husky.sh"

NOCOLOR='\033[0m'
PURPLE='\033[1;35m'
exec < /dev/tty && yarn git-cz --hook || 
echo "${PURPLE}FIX: Try upgrading git, --absolute-git-dir was introduced in v2.13${NOCOLOR}" && true